import { shuffleArr } from "../utils";

const domains = [
  ...new Array(21).fill("aol.com"),
  ...new Array(127).fill("gmail.com"),
  ...new Array(13).fill("hotmail.com"),
  ...new Array(18).fill("hotmail.co.uk"),
  ...new Array(9).fill("outlook.com"),
  ...new Array(8).fill("rocketmail.com"),
  "att.net",
  "comcast.net",
  "gmx.com",
  "googlemail.com",
  "google.com",
  "mac.com",
  "me.com",
  "mail.com",
  "msn.com",
  "live.com",
  "sbcglobal.net",
  "verizon.net",
  "yahoo.co.uk",
  "email.com",
  "fastmail.fm",
  "games.com",
  "gmx.net",
  "hush.com",
  "hushmail.com",
  "icloud.com",
  "iname.com",
  "inbox.com",
  "lavabit.com",
  "love.com",
  "pobox.com",
  "protonmail.ch",
  "protonmail.com",
  "tutanota.com",
  "tutamail.com",
  "tuta.io",
  "keemail.me",
  "safe-mail.net",
  "wow.com",
  "ygm.com",
  "ymail.com",
  "zoho.com",
  "yandex.com",
  "bellsouth.net",
  "charter.net",
  "cox.net",
  "earthlink.net",
  "juno.com",
  "btinternet.com",
  "virginmedia.com",
  "blueyonder.co.uk",
  "freeserve.co.uk",
  "live.co.uk",
  "ntlworld.com",
  "o2.co.uk",
  "orange.net",
  "sky.com",
  "virgin.net",
  "bt.com",
  "sina.com",
  "sina.cn",
  "qq.com",
  "naver.com",
  "hanmail.net",
  "foxmail.com",
  "mail.ru",
  "yandex.ru",
  "globo.com",
  "globomail.com",
];
export const emailDomains = shuffleArr(domains);
